// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvwvtTy1vnkfm_WetuFIjjkTQHZrEqrEc',
    appId: '1:386367676679:android:5cf1f812b4545e0d44a5a2',
    messagingSenderId: '386367676679',
    projectId: 'training-abdfatah',
    storageBucket: 'training-abdfatah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBstKmrDgP-tUNp24vpJEN5fIsUs7IUeT0',
    appId: '1:386367676679:ios:83cf287d01a8185e44a5a2',
    messagingSenderId: '386367676679',
    projectId: 'training-abdfatah',
    storageBucket: 'training-abdfatah.appspot.com',
    iosBundleId: 'com.example.flashchatMedium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGRz5DbdC2TucNP9oJragFr_RWcEMRKRY',
    appId: '1:386367676679:web:254962c96cec7d3644a5a2',
    messagingSenderId: '386367676679',
    projectId: 'training-abdfatah',
    authDomain: 'training-abdfatah.firebaseapp.com',
    storageBucket: 'training-abdfatah.appspot.com',
    measurementId: 'G-1C010HE6W1',
  );
}
